### ISSUE TITLE
Email address under "get involved" kicks back an error

### ISSUE THREAD

**Issue by chelle-rr** [dannng/dannng.github.io#3]
Hi DANNNG—emailing dannng@googlegroups.com kicks back a message that either the group doesn't exist or may not permit posting.

**Comment by bdietz** [comment]
Thanks! We'll be updating the site soon with links to documents open for comment. This will be fixed then.

**Comment by bdietz** [comment]
Thanks, again for pointing this out. We've swapped out the email address w/ a link to an interest survey.
