### ISSUE TITLE
Update current group membership on front page

### ISSUE THREAD

**Issue by dd388** [dannng/dannng.github.io#5]
We need to update the member list we have on our front page. This implicates a few sub-tasks as well. I'll list out what I can think off the top of my head:

* Decide whether we want to separate out by current active members and all members
* Check affiliations of current members for any updates needed
* Add in names of new folks who have joined since we last updated the page

**Comment by dd388** [comment]
Summary of email discussions about this:
* Active members will be on home page
* All members will be listed on separate page

Google Form will be used to gather how folks prefer to be listed, their affiliations, and ORCIDs

**Comment by dd388** [comment]
Assigning to Brian to implement updates for 2022 as per the above.

**Comment by bdietz** [comment]
completed pending updates being pushed next week to coincide with glossary release....and stragglers.
